### ISSUE TITLE
How to remove log area

### ISSUE THREAD

**Issue by siplabiith** [Kaljurand/dictate.js#25]
i am unable to remove log text area. i need only text which is converted from text.
what modifications shold i do in the html page https://github.com/Kaljurand/dictate.js/blob/master/demos/demo.html
![Screenshot from 2019-09-07 11-08-54](https://user-images.githubusercontent.com/47735650/64470436-85996900-d160-11e9-8760-05ff06058de1.png)

**Comment by Kaljurand** [comment]
One option is to add ``display: none`` to the CSS of ``#log``.

The other option is to remove ``<pre id="log"/>`` from the HTML. I guess you tried that but due to a bug it caused an exception. This should be now fixed
https://github.com/Kaljurand/dictate.js/commit/e2926bc7898f3f4f9e4771b42175aeb9cdf658e1
